### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by sahar-alghamdi** [udacity/FSND-Deploy-Flask-App-to-Kubernetes-Using-EKS#29]
When trying to create a stack on AWS CloudFormation using ci-cd-codepipeline.cfn.yml template, I'm getting a deprecation warning.

/var/runtime/botocore/vendored/requests/api.py:72: DeprecationWarning: You are using the put() function from 'botocore.vendored.requests'.  This dependency was removed from Botocore and will be removed from Lambda after 2021/01/30. https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/. Install the requests package, 'import requests' directly, and use the requests.put() function instead.

**Comment by rawalpurvi** [comment]
When trying to create a stack on AWS using this yml file, I am getting the following error and causes the Stack creation to fail:

`Custom Resource failed to stabilize in expected time. Ifyou are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated  version.`

**Comment by SudKul** [comment]
Hi @sahar-alghamdi 
Though we are a little late to respond, we suggest you raise a [Knowledge thread](https://knowledge.udacity.com/) with a few more details, such as:

- What are your OS and terminal?
- Classroom page link? Which particular step is causing the issue?
- Command that is causing the warning?
- Provide a link to your Github repos, containing the template file.

Happy Learning
Udacity
